### ISSUE TITLE
Create Payments missing summarizeErrors parameter

### ISSUE THREAD

**Issue by ashickton** [XeroAPI/Xero-NetStandard#154]
Xero.NetStandard.OAuth2             {0.4.1}
Xero.NetStandard.OAuth2Client       {0.0.3}

CreatePaymentsAsync is missing the summarizeErrors parameter

We need to be able to create payments in a batch and pass in summarizeErrors=false so that we can handle any payments that could not be created.

The old Xero-Net wrapper had this option, so I assume that the underlying API still supports the option.

**Comment by adamsadler** [comment]
For what it's worth, the actual API does still support this, but it's the OpenAPI description of the API that is lacking these features. This wrapper library is generated using the OpenAPI yaml files, rather than being hand-coded (as I gather!).

I was going to add this very problem as an issue in https://github.com/XeroAPI/Xero-OpenAPI so that the missing elements can be added there - but maybe you could and link back?

**Comment by SidneyAllen** [comment]
@ashickton - I've opened an issue on our OpenAPi Spec repo

https://github.com/XeroAPI/Xero-OpenAPI/issues/167

**Comment by jenksguo** [comment]
@ashickton 

Addressed in [release 0.4.3](https://github.com/XeroAPI/Xero-NetStandard/releases/tag/v0.4.3)

It should work if you pass in "false" in the parameter of the method now. 

Thanks for reporting the error.

**Comment by mbrightenfield** [comment]
> 
> 
> @ashickton
> 
> Addressed in [release 0.4.3](https://github.com/XeroAPI/Xero-NetStandard/releases/tag/v0.4.3)
> 
> It should work if you pass in "false" in the parameter of the method now.
> 
> Thanks for reporting the error.

Forgive me if I'm missing something here but I'm still not seeing summarizeErrors as a parameter for the CreatePaymentsAsync method?

I was using nuget package Xero.NetStandard.OAuth2 {0.4.5}
I updated nuget package to Xero.NetStandard.OAuth2 {2.0.0} and I'm still not seeing the method updated.

Additionally I've downloaded both the raw versions 0.4.3 and 2.0.0 from github directly and I'm not seeing the method updated.

Am I missing something here?

**Comment by wobinb** [comment]
@mbrightenfield It would appear that the recent update was to resolve another related summarizeErrors issue. The fact that the argument is missing is due to an issue within the OpenAPI spec. I've just submitted a PR for this here: https://github.com/XeroAPI/Xero-OpenAPI/pull/206

**Comment by mbrightenfield** [comment]
This has now been addressed as of SDK 2.2.0
[https://github.com/XeroAPI/Xero-NetStandard/releases/tag/v2.2.0](url)
